export const products = [
  {
    id: 1,
    name: "Beetroot Powder",
    description: "100% Natural | 250g",
    price: 299.0,
    image: "/images/beetroot-powder.jpg",
    longDescription:
      "Our premium Beetroot Powder is made from 100% organic beetroots, carefully dehydrated and ground to preserve all the natural nutrients. Rich in antioxidants, vitamins, and minerals, this versatile powder can be added to smoothies, soups, or baked goods for a nutritional boost.",
    benefits: [
      "Boosts Exercise Performance",
      "Supports Heart Health",
      "Improves Digestion",
      "Enhances Detoxification",
      "Promotes Healthy Skin",
      "Supports Brain Health",
      "Aids in Weight Management",
    ],
    nutritionFacts: [
      { nutrient: "Calories", amount: "350 kcal" },
      { nutrient: "Carbohydrates", amount: "81.7 g" },
      { nutrient: "Dietary Fiber", amount: "15.6 g" },
      { nutrient: "Sugars", amount: "8.5 g" },
      { nutrient: "Protein", amount: "10.3 g" },
      { nutrient: "Fat", amount: "0.4 g" },
      { nutrient: "Vitamin C", amount: "7.8 mg" },
      { nutrient: "Vitamin B6", amount: "0.1 mg" },
      { nutrient: "Potassium", amount: "1,040 mg" },
      { nutrient: "Calcium", amount: "25 mg" },
      { nutrient: "Magnesium", amount: "81 mg" },
      { nutrient: "Iron", amount: "3.4 mg" },
      { nutrient: "Phosphorus", amount: "93 mg" },
      { nutrient: "Sodium", amount: "1 mg" },
    ],
    usage: "Add 1-2 teaspoons to smoothies, juices, soups, or baked goods. Store in a cool, dry place after opening.",
    reviews: [
      {
        id: 1,
        name: "Jane Smith",
        rating: 5,
        date: "May 15, 2023",
        comment: "Excellent quality powder! Mixes well and tastes great in my morning smoothie.",
      },
      {
        id: 2,
        name: "John Doe",
        rating: 4,
        date: "April 22, 2023",
        comment: "Good product, but the packaging could be improved. The powder itself is fantastic.",
      },
    ],
  },
  {
    id: 2,
    name: "Banana Powder",
    description: "100% Natural | 200g",
    price: 249.0,
    image: "/images/banana-powder.jpg",
    longDescription:
      "Our Banana Powder is made from ripe, organic bananas that are carefully dehydrated and ground into a fine powder. It retains all the natural sweetness and nutritional benefits of fresh bananas, making it perfect for adding to smoothies, baked goods, and more.",
    benefits: [
      "Rich in Nutrients",
      "Supports Digestive Health",
      "Boosts Energy Levels",
      "Improves Heart Health",
      "Helps with Weight Management",
      "Enhances Skin Health",
      "Supports Bone Health",
    ],
    nutritionFacts: [
      { nutrient: "Calories", amount: "357 kcal" },
      { nutrient: "Carbohydrates", amount: "88.5 g" },
      { nutrient: "Dietary Fiber", amount: "12.5 g" },
      { nutrient: "Sugars", amount: "28.5 g" },
      { nutrient: "Protein", amount: "3.6 g" },
      { nutrient: "Fat", amount: "1.3 g" },
      { nutrient: "Vitamin A", amount: "64 IU" },
      { nutrient: "Vitamin C", amount: "11 mg" },
      { nutrient: "Vitamin B6", amount: "0.4 mg" },
      { nutrient: "Potassium", amount: "537 mg" },
      { nutrient: "Calcium", amount: "35 mg" },
      { nutrient: "Magnesium", amount: "37 mg" },
      { nutrient: "Iron", amount: "2.6 mg" },
      { nutrient: "Phosphorus", amount: "85 mg" },
    ],
    usage:
      "Add 1-2 tablespoons to smoothies, yogurt, oatmeal, or baking recipes. Store in a cool, dry place after opening.",
    reviews: [
      {
        id: 1,
        name: "Sarah Johnson",
        rating: 5,
        date: "June 10, 2023",
        comment: "Love the natural sweetness this adds to my morning smoothies!",
      },
      {
        id: 2,
        name: "Michael Brown",
        rating: 5,
        date: "May 5, 2023",
        comment: "Great quality product. I use it in my homemade protein bars.",
      },
    ],
  },
  {
    id: 3,
    name: "Carrot Powder",
    description: "100% Natural | 200g",
    price: 249.0,
    image: "/images/carrot-powder.jpg",
    longDescription:
      "Our Carrot Powder is made from fresh, organic carrots that are carefully dehydrated and ground into a fine powder. It retains all the nutritional benefits of fresh carrots, including beta-carotene and other essential vitamins and minerals.",
    benefits: [
      "Promotes Eye Health",
      "Supports Skin Health",
      "Boosts Immune Function",
      "Improves Digestion",
      "Enhances Heart Health",
      "Rich in Antioxidants",
      "Supports Bone Health",
    ],
    nutritionFacts: [
      { nutrient: "Calories", amount: "375 kcal" },
      { nutrient: "Carbohydrates", amount: "87.4 g" },
      { nutrient: "Dietary Fiber", amount: "28 g" },
      { nutrient: "Sugars", amount: "37.5 g" },
      { nutrient: "Protein", amount: "9.2 g" },
      { nutrient: "Fat", amount: "0.6 g" },
      { nutrient: "Vitamin A", amount: "16,706 IU" },
      { nutrient: "Vitamin C", amount: "3.6 mg" },
      { nutrient: "Vitamin B6", amount: "0.2 mg" },
      { nutrient: "Potassium", amount: "1,922 mg" },
      { nutrient: "Calcium", amount: "39 mg" },
      { nutrient: "Magnesium", amount: "59 mg" },
      { nutrient: "Iron", amount: "3.2 mg" },
      { nutrient: "Phosphorus", amount: "125 mg" },
      { nutrient: "Sodium", amount: "69 mg" },
    ],
    usage: "Add 1-2 teaspoons to smoothies, soups, sauces, or baked goods. Store in a cool, dry place after opening.",
    reviews: [
      {
        id: 1,
        name: "David Wilson",
        rating: 4,
        date: "April 18, 2023",
        comment: "Great way to add nutrients to my diet. I mix it into my morning juice.",
      },
      {
        id: 2,
        name: "Emily Clark",
        rating: 5,
        date: "March 22, 2023",
        comment: "Excellent product! I use it in my homemade baby food for added nutrition.",
      },
    ],
  },
  {
    id: 4,
    name: "Lemon Powder",
    description: "100% Natural | 150g",
    price: 279.0,
    image: "/images/lemon-powder.jpg",
    longDescription:
      "Our Lemon Powder is made from fresh, organic lemons that are carefully dehydrated and ground into a fine powder. It retains the tangy flavor and nutritional benefits of fresh lemons, making it perfect for adding to drinks, desserts, and savory dishes.",
    benefits: [
      "Rich in Vitamin C",
      "Supports Immune System",
      "Aids in Digestion",
      "Promotes Skin Health",
      "Detoxifies the Body",
      "Supports Weight Loss",
      "Balances pH Levels",
      "Improves Hydration",
      "Boosts Heart Health",
      "Fights Inflammation",
    ],
    nutritionFacts: [
      { nutrient: "Calories", amount: "290 kcal" },
      { nutrient: "Protein", amount: "4.0 g" },
      { nutrient: "Fat", amount: "1.0 g" },
      { nutrient: "Carbohydrates", amount: "90 g" },
      { nutrient: "Fiber", amount: "25 g" },
      { nutrient: "Sugars", amount: "3.0 g" },
      { nutrient: "Calcium", amount: "150 mg" },
      { nutrient: "Iron", amount: "3.0 mg" },
      { nutrient: "Magnesium", amount: "70 mg" },
      { nutrient: "Vitamin C", amount: "120 mg" },
      { nutrient: "Potassium", amount: "1,000 mg" },
      { nutrient: "Phosphorus", amount: "70 mg" },
      { nutrient: "Zinc", amount: "0.7 mg" },
    ],
    usage:
      "Add 1/2-1 teaspoon to water, tea, smoothies, dressings, or marinades. Store in a cool, dry place after opening.",
    reviews: [
      {
        id: 1,
        name: "Jessica Taylor",
        rating: 5,
        date: "June 5, 2023",
        comment: "Love the tangy flavor this adds to my water and tea. Great alternative to fresh lemons!",
      },
      {
        id: 2,
        name: "Robert Johnson",
        rating: 4,
        date: "May 12, 2023",
        comment: "Good product. I use it in my salad dressings and marinades.",
      },
    ],
  },
  {
    id: 5,
    name: "Coconut Powder",
    description: "100% Natural | 200g",
    price: 249.0,
    image: "/images/coconut-powder.jpg",
    longDescription:
      "Our Coconut Powder is made from fresh, organic coconuts that are carefully dehydrated and ground into a fine powder. It retains all the natural flavor and nutritional benefits of fresh coconuts, making it perfect for adding to smoothies, baked goods, and more.",
    benefits: [
      "Supports Heart Health",
      "Promotes Digestive Health",
      "Boosts Immune System",
      "Enhances Skin Health",
      "Aids in Weight Management",
      "Rich in Healthy Fats",
    ],
    nutritionFacts: [
      { nutrient: "Calories", amount: "660 kcal" },
      { nutrient: "Carbohydrates", amount: "22.5 g" },
      { nutrient: "Dietary Fiber", amount: "15 g" },
      { nutrient: "Sugars", amount: "6 g" },
      { nutrient: "Protein", amount: "6.3 g" },
      { nutrient: "Fat", amount: "64.5 g" },
      { nutrient: "Vitamin C", amount: "3.3 mg" },
      { nutrient: "Vitamin E", amount: "0.24 mg" },
      { nutrient: "Vitamin B6", amount: "0.1 mg" },
      { nutrient: "Potassium", amount: "500 mg" },
      { nutrient: "Calcium", amount: "14 mg" },
      { nutrient: "Magnesium", amount: "90 mg" },
      { nutrient: "Iron", amount: "3.3 mg" },
      { nutrient: "Phosphorus", amount: "220 mg" },
      { nutrient: "Sodium", amount: "10 mg" },
    ],
    usage:
      "Add 1-2 tablespoons to smoothies, curries, baked goods, or use as a dairy-free alternative in recipes. Store in a cool, dry place after opening.",
    reviews: [
      {
        id: 1,
        name: "Amanda Lee",
        rating: 5,
        date: "April 30, 2023",
        comment: "Perfect for my dairy-free recipes! Great coconut flavor and mixes well.",
      },
      {
        id: 2,
        name: "Thomas Brown",
        rating: 4,
        date: "March 15, 2023",
        comment: "Good quality product. I use it in my morning smoothies for added flavor and nutrition.",
      },
    ],
  },
  {
    id: 6,
    name: "Moringa Powder",
    description: "100% Natural | 150g",
    price: 349.0,
    image: "/images/moringa-powder.jpg",
    longDescription:
      "Our Moringa Powder is made from fresh, organic moringa leaves that are carefully dehydrated and ground into a fine powder. Known as a superfood, moringa is packed with nutrients, antioxidants, and bioactive compounds that offer numerous health benefits.",
    benefits: [
      "Rich in Nutrients",
      "Boosts Immune System",
      "Anti-Inflammatory Effects",
      "Regulates Blood Sugar Levels",
      "Supports Heart Health",
      "Improves Skin Health",
      "Promotes Digestive Health",
    ],
    nutritionFacts: [
      { nutrient: "Calories", amount: "370 kcal" },
      { nutrient: "Protein", amount: "27 g" },
      { nutrient: "Fat", amount: "6.0 g" },
      { nutrient: "Carbohydrates", amount: "60 g" },
      { nutrient: "Fiber", amount: "19 g" },
      { nutrient: "Sugars", amount: "2.6 g" },
      { nutrient: "Calcium", amount: "1,400 mg" },
      { nutrient: "Iron", amount: "28.2 mg" },
      { nutrient: "Magnesium", amount: "450 mg" },
      { nutrient: "Vitamin A", amount: "18,000 IU" },
      { nutrient: "Vitamin C", amount: "220 mg" },
      { nutrient: "Potassium", amount: "1,100 mg" },
      { nutrient: "Phosphorus", amount: "180 mg" },
      { nutrient: "Zinc", amount: "4.0 mg" },
    ],
    usage:
      "Add 1 teaspoon to smoothies, juices, soups, or sprinkle over salads. Start with small amounts and gradually increase. Store in a cool, dry place after opening.",
    reviews: [
      {
        id: 1,
        name: "Michelle Davis",
        rating: 5,
        date: "June 15, 2023",
        comment: "Amazing superfood! I've noticed increased energy since adding this to my daily routine.",
      },
      {
        id: 2,
        name: "James Wilson",
        rating: 4,
        date: "May 20, 2023",
        comment: "Good quality moringa powder. The taste is strong but works well in smoothies with fruit.",
      },
    ],
  },
  {
    id: 7,
    name: "Tomato Powder",
    description: "100% Natural | 150g",
    price: 269.0,
    image: "/images/tomato-powder.jpg",
    longDescription:
      "Our Tomato Powder is made from fresh, organic tomatoes that are carefully dehydrated and ground into a fine powder. It retains all the flavor and nutritional benefits of fresh tomatoes, making it perfect for adding to soups, sauces, and more.",
    benefits: [
      "Promotes Heart Health",
      "Enhances Skin Health",
      "Rich in Antioxidants",
      "Boosts Immune System",
      "Supports Digestive Health",
      "Aids in Weight Management",
    ],
    nutritionFacts: [
      { nutrient: "Calories", amount: "323 kcal" },
      { nutrient: "Carbohydrates", amount: "73.5 g" },
      { nutrient: "Dietary Fiber", amount: "34.5 g" },
      { nutrient: "Sugars", amount: "22 g" },
      { nutrient: "Protein", amount: "13 g" },
      { nutrient: "Fat", amount: "1.8 g" },
      { nutrient: "Vitamin A", amount: "1,500 IU" },
      { nutrient: "Vitamin C", amount: "58.4 mg" },
      { nutrient: "Vitamin K", amount: "4.2 mcg" },
      { nutrient: "Potassium", amount: "2,300 mg" },
      { nutrient: "Calcium", amount: "100 mg" },
      { nutrient: "Magnesium", amount: "90 mg" },
      { nutrient: "Iron", amount: "3.5 mg" },
      { nutrient: "Phosphorus", amount: "130 mg" },
      { nutrient: "Sodium", amount: "75 mg" },
    ],
    usage:
      "Add 1-2 tablespoons to soups, sauces, marinades, or use as a seasoning. Rehydrate with water for tomato paste. Store in a cool, dry place after opening.",
    reviews: [
      {
        id: 1,
        name: "Daniel Green",
        rating: 5,
        date: "April 10, 2023",
        comment: "Great for making quick tomato sauce when I'm out of fresh tomatoes. Good flavor!",
      },
      {
        id: 2,
        name: "Sophia Martinez",
        rating: 4,
        date: "March 5, 2023",
        comment: "Convenient product for adding tomato flavor to dishes. I use it in my homemade spice blends.",
      },
    ],
  },
  {
    id: 8,
    name: "Curry Leaves Powder",
    description: "100% Natural | 100g",
    price: 229.0,
    image: "/images/curry-leaves-powder.jpg",
    longDescription:
      "Our Curry Leaves Powder is made from fresh, organic curry leaves that are carefully dehydrated and ground into a fine powder. It retains all the aromatic flavor and nutritional benefits of fresh curry leaves, making it perfect for adding to curries, soups, and more.",
    benefits: [
      "Rich in Antioxidants",
      "Supports Healthy Digestion",
      "Promotes Healthy Hair Growth",
      "Regulates Blood Sugar Levels",
      "Boosts Liver Health",
      "Improves Skin Health",
      "Supports Weight Loss",
      "Anti-Inflammatory Effects",
      "Rich in Nutrients",
      "Improves Eye Health",
    ],
    nutritionFacts: [
      { nutrient: "Calories", amount: "325 kcal" },
      { nutrient: "Protein", amount: "6.0 g" },
      { nutrient: "Fat", amount: "6.0 g" },
      { nutrient: "Carbohydrates", amount: "60 g" },
      { nutrient: "Fiber", amount: "10 g" },
      { nutrient: "Sugars", amount: "0 g" },
      { nutrient: "Calcium", amount: "830 mg" },
      { nutrient: "Iron", amount: "3.3 mg" },
      { nutrient: "Magnesium", amount: "150 mg" },
      { nutrient: "Vitamin A", amount: "7,500 IU" },
      { nutrient: "Vitamin C", amount: "45 mg" },
      { nutrient: "Potassium", amount: "1,100 mg" },
      { nutrient: "Phosphorus", amount: "130 mg" },
      { nutrient: "Zinc", amount: "0.6 mg" },
    ],
    usage:
      "Add 1/2-1 teaspoon to curries, soups, rice dishes, or vegetable preparations. Store in a cool, dry place after opening.",
    reviews: [
      {
        id: 1,
        name: "Priya Patel",
        rating: 5,
        date: "May 25, 2023",
        comment: "Authentic flavor and aroma! Perfect for my Indian cooking when fresh curry leaves aren't available.",
      },
      {
        id: 2,
        name: "Raj Singh",
        rating: 5,
        date: "April 15, 2023",
        comment: "Excellent quality curry leaf powder. Adds great flavor to my dishes.",
      },
    ],
  },
  {
    id: 9,
    name: "Papaya Leaves Powder",
    description: "100% Natural | 100g",
    price: 299.0,
    image: "/images/papaya-leaves-powder.jpg",
    longDescription:
      "Our Papaya Leaves Powder is made from fresh, organic papaya leaves that are carefully dehydrated and ground into a fine powder. Known for their medicinal properties, papaya leaves are packed with nutrients and enzymes that offer numerous health benefits.",
    benefits: [
      "Supports Immune System",
      "Promotes Digestive Health",
      "Boosts Platelet Count",
      "Anti-Inflammatory Properties",
      "Improves Skin Health",
      "Supports Liver Health",
      "Regulates Blood Sugar Levels",
      "Rich in Antioxidants",
      "Detoxifies the Body",
      "Promotes Healthy Menstrual Cycle",
    ],
    nutritionFacts: [
      { nutrient: "Calories", amount: "400 kcal" },
      { nutrient: "Protein", amount: "15.0 g" },
      { nutrient: "Fat", amount: "2.0 g" },
      { nutrient: "Carbohydrates", amount: "70 g" },
      { nutrient: "Fiber", amount: "24 g" },
      { nutrient: "Sugars", amount: "5.0 g" },
      { nutrient: "Calcium", amount: "350 mg" },
      { nutrient: "Iron", amount: "5.0 mg" },
      { nutrient: "Magnesium", amount: "160 mg" },
      { nutrient: "Vitamin C", amount: "90 mg" },
      { nutrient: "Potassium", amount: "1,100 mg" },
      { nutrient: "Phosphorus", amount: "90 mg" },
      { nutrient: "Zinc", amount: "1.0 mg" },
    ],
    usage:
      "Add 1/2-1 teaspoon to water, tea, or smoothies. Start with small amounts and gradually increase. Store in a cool, dry place after opening.",
    reviews: [
      {
        id: 1,
        name: "Lisa Chen",
        rating: 5,
        date: "June 20, 2023",
        comment: "Great product for immune support. I take it regularly during flu season.",
      },
      {
        id: 2,
        name: "Mark Thompson",
        rating: 4,
        date: "May 10, 2023",
        comment: "Good quality papaya leaf powder. The taste is bitter but worth it for the health benefits.",
      },
    ],
  },
]

export function getProductById(id: number) {
  return products.find((product) => product.id === id)
}

export function getRelatedProducts(id: number, limit = 4) {
  return products.filter((product) => product.id !== id).slice(0, limit)
}

